// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe0MzQgImxK9jP1bOPEBjjj2oHRT-s234',
    appId: '1:145741739132:web:dc82dcd39202d92c9285f9',
    messagingSenderId: '145741739132',
    projectId: 'abastecimento-de-veiculos',
    authDomain: 'abastecimento-de-veiculos.firebaseapp.com',
    storageBucket: 'abastecimento-de-veiculos.firebasestorage.app',
    measurementId: 'G-995D0LV5SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHifUxxppPhulYYXZzBv5FgHgbLgBYsXo',
    appId: '1:145741739132:android:158f20a33a47f8e59285f9',
    messagingSenderId: '145741739132',
    projectId: 'abastecimento-de-veiculos',
    storageBucket: 'abastecimento-de-veiculos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp9t3i6FNFUPbagfqk5OvsZjcTWsidFr8',
    appId: '1:145741739132:ios:519c1aca769fb5179285f9',
    messagingSenderId: '145741739132',
    projectId: 'abastecimento-de-veiculos',
    storageBucket: 'abastecimento-de-veiculos.firebasestorage.app',
    iosBundleId: 'com.example.abastecimentoCarros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp9t3i6FNFUPbagfqk5OvsZjcTWsidFr8',
    appId: '1:145741739132:ios:519c1aca769fb5179285f9',
    messagingSenderId: '145741739132',
    projectId: 'abastecimento-de-veiculos',
    storageBucket: 'abastecimento-de-veiculos.firebasestorage.app',
    iosBundleId: 'com.example.abastecimentoCarros',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe0MzQgImxK9jP1bOPEBjjj2oHRT-s234',
    appId: '1:145741739132:web:a8492c45caeccbfd9285f9',
    messagingSenderId: '145741739132',
    projectId: 'abastecimento-de-veiculos',
    authDomain: 'abastecimento-de-veiculos.firebaseapp.com',
    storageBucket: 'abastecimento-de-veiculos.firebasestorage.app',
    measurementId: 'G-B7PHQ1NTCY',
  );
}
